server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.ocr-eureka.credentials.uri:http://172.27.59.120:8761/eureka/}
  instance:
    hostname: ${vcap.application.uris[0]:pushpendrad}
    metadataMap:
      instanceId: web_pushpendrad
---
spring:
  profiles: cloud
eureka:
  instance:
    nonSecurePort: 80
zuul:
  routes:
    races: /races/**
    participants: /paticipants/**
